[package]
name = "kcshot-data"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
gsettings-macro = "0.2.0"
gtk4.workspace = true
