warn = [
    "unused_qualifications",
    "clippy::match_same_arms",
    "clippy::trivially_copy_pass_by_ref",
    "clippy::semicolon_if_nothing_returned",
    "clippy::redundant_closure_for_method_calls",
    "clippy::items_after_statements",
    "clippy::useless_conversion",
    "clippy::dbg_macro",
    "clippy::unnecessary_wraps",
]
