on:
  push:
    branches: [master]
  pull_request:

name: CI

env:
  KCSHOT_UBUNTU_DEPS: libdbus-1-dev pkg-config libgtk-4-dev libcairo-gobject2 libcairo2-dev

permissions:
  contents: read

# Given that this job can get quite expensive at times, we ensure that for a given PR/branch,
# we cancel previous jobs on new pushes.
# See:
#  - this Stackoverflow post: https://stackoverflow.com/a/72408109
#  - GitHub docs on the matter: https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  rustfmt:
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@nightly
        id: toolchain-install
        with:
          components: rustfmt
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ steps.toolchain-install.outputs.cachekey }}-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock')}}
      - run: cargo +nightly fmt --all -- --check

  build:
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ubuntu-22.04
    steps:
      - run: |
          sudo apt-get update -y
          sudo apt install -y $KCSHOT_UBUNTU_DEPS
      - uses: actions/checkout@v3
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        id: toolchain-install
        with:
          components: clippy
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ steps.toolchain-install.outputs.cachekey }}-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock')}}-lint
      - name: clippy
        run: cargo clippy -- -D warnings
  test:
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ubuntu-22.04
    steps:
      - run: |
          sudo apt-get update -y
          sudo apt install -y $KCSHOT_UBUNTU_DEPS
      - uses: actions/checkout@v3
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        id: toolchain-install
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ steps.toolchain-install.outputs.cachekey }}-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock')}}-test
      - name: test
        run: cargo test
