on:
  push:
    branches: [master]
  pull_request:

name: CI

env:
  KCSHOT_UBUNTU_DEPS: libdbus-1-dev pkg-config libgtk-4-dev libcairo-gobject2 libcairo2-dev

jobs:
  rustfmt:
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo +nightly fmt --all -- --check

  build:
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ubuntu-22.04
    steps:
      - run: |
          sudo apt-get update -y
          sudo apt install -y $KCSHOT_UBUNTU_DEPS
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: compile
        run: cargo build
      - name: clippy
        run: cargo clippy
  test:
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ubuntu-22.04
    steps:
      - run: |
          sudo apt-get update -y
          sudo apt install -y $KCSHOT_UBUNTU_DEPS
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: test
        run: cargo test
