on:
  push:
    branches: [master]
  pull_request:

name: Codespell

permissions:
  contents: read

jobs:
  codespell:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          ignore_words_list: crate,ine
